[workspace]
members = [
    "node",
    "runtime",
    # custom
    "ocw-common",
    "pallets/ocw-circuits",
    "pallets/ocw-garble",
    "pallets/tx-validation",
]

[profile.release]
panic = "unwind"
[profile.dev]
panic = "unwind"